### ISSUE TITLE
EPIC: UI/UX Redesign

### ISSUE THREAD

**Issue by esparr** [TeamProductionSystem/Team_Production_System#280]
- [ ] [Build a style guide#265](https://github.com/TeamProductionSystem/Momentors_Frontend/issues/265)
- [ ] [Design Momentors Logo#269](https://github.com/TeamProductionSystem/Momentors_Frontend/issues/269)
- [ ] [Users experience a updated, easy to use navigation bar#268](https://github.com/TeamProductionSystem/Momentors_Frontend/issues/268)
- [ ] [As a mentor, I want to easily be able to add availability from my profile#278](https://github.com/TeamProductionSystem/Momentors_Frontend/issues/278)
- [ ] [Mentors can look at their mentor sessions information from their profile page#266](https://github.com/TeamProductionSystem/Momentors_Frontend/issues/266)

**Comment by esparr** [comment]
@villeryd I added this epic so we can keep track of the tickets associated with this redesign. Let me know what stories you see us needing out of this redesign and I will get them added =)
